# -*- coding: utf-8 -*-
{
    'name': 'Hospital Management Hima',
    'sequence': -100,
    'version': '16.0.1.0',
    'category': '',
    'summary': 'Hospital Management Software',
    'description': """Hospital Management Software""",
    'depends': ['sale',
                'mail',
                'report_xlsx',
                'stock',
                # 'board'
                ],
    'data': [
        'security/ir.model.access.csv',
        'data/data.xml',
        'data/patient.tag.csv',
        'data/patient_tag_data.xml',
        'wizard/all_patient_report_view.xml',
        'wizard/appointment_report_view.xml',
        'wizard/cancel_appointment_view.xml',
        'wizard/create_appointment_view.xml',
        'wizard/search_appointment_view.xml',
        # 'views/dashboard.xml',
        'views/appointment_view.xml',
        'views/doctor_view.xml',
        'views/kids_view.xml',
        'views/menu.xml',
        'views/odoo_playground_view.xml',
        'views/partner_view.xml',
        'views/patient_gender_view.xml',
        'views/patient_tag_view.xml',
        'views/patient_view.xml',
        'views/res_config_settings_views.xml',
        'views/sale_view.xml',
        'report/all_patient_list.xml',
        'report/appointment_details.xml',
        'report/patient_card.xml',
        'report/patient_details_template.xml',
        'report/report.xml'

    ],
    'installable': True,
    'license': 'LGPL-3',
    'application': True,
    'autoinstall': False,
}
